[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "sequence-logger"
version = "0.1.0"
description = "A simple logger package"
authors = ["Your Name <your.email@example.com>"]
license = "MIT"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
packages = [
    { include = "sequence_logger", from = "src" }
]

[tool.poetry.dependencies]
python = ">=3.7"
