from .nidc_power_source_dc_voltage_client import NIDCPowerSourceDCVoltageClient
from .ni_dmm_measurement_client import NIDmmMeasurementClient

nidcpowersourcedcvoltageclient = NIDCPowerSourceDCVoltageClient()
nidmmmeasurementclient = NIDmmMeasurementClient()